
### Create User
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Nathália Duarte",
    "email": "duarte.nathalia@hotmail.com",
    "password": "hdjalm12dh8e7"
}


### Add a friend
POST http://localhost:3003/users/friends
Content-Type: application/json

{
    "userId": "dc06a564-482a-4973-91bf-0aa385e0fc54",
    "friendId": "2daec062-4f83-4e59-9eb7-718c70499536"
}


### Delete a friend
DELETE http://localhost:3003/users/friends/2daec062-4f83-4e59-9eb7-718c70499536
Content-Type: application/json

{
    "friendId": "dc06a564-482a-4973-91bf-0aa385e0fc54"
}


### Get Friends By User Id
GET http://localhost:3003/users/friends/2daec062-4f83-4e59-9eb7-718c70499536
Content-Type: application/json


### Search Users
GET http://localhost:3003/users?search=nath
Content-Type: application/json


### Create Post
POST http://localhost:3003/posts
Content-Type: application/json

{
    "photo": "https://fastly.picsum.photos/id/13/2500/1667.jpg?hmac=SoX9UoHhN8HyklRA4A3vcCWJMVtiBXUg0W4ljWTor7s",
    "description": "Fim de tarde na praia",
    "type": "normal",
    "authorId": "dc06a564-482a-4973-91bf-0aa385e0fc54"
}


### Get Post By Id
GET http://localhost:3003/posts/04bd6186-f579-4148-bd18-ecba8d0ffb99
Content-Type: application/json


### Get All Posts
GET http://localhost:3003/posts?page=1&size=5
Content-Type: application/json


### Like Post
POST http://localhost:3003/posts/likes/4daf124c-0d9a-46fe-8318-b957c10f8bfb
Content-Type: application/json

{
    "userId": "2daec062-4f83-4e59-9eb7-718c70499536"
}


### Deslike Post
DELETE http://localhost:3003/posts/likes/4daf124c-0d9a-46fe-8318-b957c10f8bfb
Content-Type: application/json

{
    "userId": "2daec062-4f83-4e59-9eb7-718c70499536"
}


### Get Likes By Post Id
GET http://localhost:3003/posts/likes/4daf124c-0d9a-46fe-8318-b957c10f8bfb
Content-Type: application/json


### Comment on Post
POST http://localhost:3003/posts/comments/4daf124c-0d9a-46fe-8318-b957c10f8bfb
Content-Type: application/json

{
    "comment": "Adorei!!",
    "userId": "dc06a564-482a-4973-91bf-0aa385e0fc54"
}


### Get Comments By Post Id
GET http://localhost:3003/posts/comments/4daf124c-0d9a-46fe-8318-b957c10f8bfb
Content-Type: application/json