POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "Gabriel Silva Só",
    "email": "gabriel.silvaso@hotmail.com",
    "password": "456321uhuias"
}

###

POST http://localhost:3003/posts
Content-Type: application/json

{
    "photo": "https://fastly.picsum.photos/id/42/3456/2304.jpg?hmac=dhQvd1Qp19zg26MEwYMnfz34eLnGv8meGk_lFNAJR3g",
    "description": "Café da tarde em ótima companhia",
    "type": "normal",
    "authorId": "2daec062-4f83-4e59-9eb7-718c70499536"
}

###

GET http://localhost:3003/posts/04bd6186-f579-4148-bd18-ecba8d0ffb99
Content-Type: application/json

###

GET http://localhost:3003/posts
Content-Type: application/json

###

POST http://localhost:3003/users/friends
Content-Type: application/json

{
    "userId": "618e9310-aacc-417c-bcbd-c215f1346fae",
    "friendId": "2daec062-4f83-4e59-9eb7-718c70499536"
}

###

POST http://localhost:3003/users/friends/618e9310-aacc-417c-bcbd-c215f1346fae
Content-Type: application/json

{
    "friendId": "2daec062-4f83-4e59-9eb7-718c70499536"
}

###

GET http://localhost:3003/users/friends/2daec062-4f83-4e59-9eb7-718c70499536
Content-Type: application/json
